pipeline {
    agent any
 
    stages {
	
        stage('Checkout') {
            steps {
                // Check out code from the GitHub repository
                script {
                    def gitCredentials = credentials('Srinidhi1006') // Replace with your credentials ID
                    checkout([$class: 'GitSCM', 
                         branches: [[name: 'master']], 
                         userRemoteConfigs: [[url: 'https://github.com/Srinidhi1006/jenkinsRepo.git', Srinidhi1006: gitCredentials]]])
                }
            }
        }
		stage("Check API stauts"){
		steps{
		echo "Check API status"
			HTTP Method: GET 
            URL: https://localhost:9164/management/applications?carbonAppName=helloWorldCompositeExporter
            Header Name: Authorization
			Header Value: Bearer eyJraWQiOiIxY2ViNzdiMC1hMTU0LTRmNTktYTVjNS05ZjZhNzJmMGFkN2QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvMDowOjA6MDowOjA6MDoxOjkxNjRcLyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjk1MTI0NjI2LCJzY29wZSI6ImFkbWluIn0.idmZx5D24Ng3FtQaiXI608K1043abo_xFQLsyE0w3njz2OGbn78ncx59_zxnmpDU2xwyBMCKGWDsZf3-GB5kmJhCgjGdkJncivm18ZCAUhXguLE0JFOz8tfHh-LGR9UGIDLZ3vp-my0wZzLUAS_lQUJEcO0jSJ5c5-7-rH5TqZR9h1Zlw5qFnZCFpR9Yk0E_xA4NpUjcigabuNt4wbwyfevOpWTMaDlR6SowJ3f2A9x6sQt9HLW2E0BYIHfrTySZdCL8UkjVh-8svCH9ppE8OvjrV8wTRcNB2Llz5TCAlyWY9C-uX-qNbI3ALDUhHBcF7dMubmjXoWmRqrluJqEGxg
			}
			}
		
 
       stage("Build in Maven"){
	   steps {

            echo "Enter Build in Maven"


         bat (returnStdout: true, script: "cd C:/ProgramData/Jenkins/.jenkins/workspace/HelloSampleProject_master/HelloWorld && mvn clean install -Dmaven.test.skip=true || echo success")

          echo "Exit Build in Maven"


        }
		}
 
        // Add more stages for testing, deployment, etc.
    }
}
